// data/products.js
import { Product } from "@/components/types/Product";

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Gaming Mouse",
    price: 49.99,
    rating: 5,
    numberRating: 102,
    image: "/img1.avif",
    badge: "New",
    isFavourite: false,
    latest: true,
    bestSeller: false,
    category: "Gamepad",
  },
  {
    id: 2,
    name: "Mechanical RGB Keyboard",
    price: 89.99,
    rating: 5,
    numberRating: 87,
    image: "/img2.avif",
    badge: "Hot",
    isFavourite: true,
    latest: true,
    bestSeller: false,
    category: "Computer",
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    price: 39.99,
    rating: 4,
    numberRating: 65,
    image: "/img 3.avif",
    badge: "Sale",
    isFavourite: false,
    latest: true,
    bestSeller: false,
    category: "Headphone",
  },
  {
    id: 4,
    name: "Noise Headphones",
    price: 129.99,
    rating: 5,
    numberRating: 150,
    image: "/img4.avif",
    badge: "Best Seller",
    isFavourite: true,
    latest: true,
    bestSeller: false,
    category: "Headphone",
  },
  {
    id: 5,
    name: "True Wireless Earbuds",
    price: 59.99,
    rating: 4,
    numberRating: 98,
    image: "/img5.jpg",
    badge: "Trending",
    isFavourite: false,
    latest: true,
    bestSeller: false,
    category: "Headphone",
  },
  {
    id: 6,
    name: "Smartwatch Series X",
    price: 199.99,
    rating: 5,
    numberRating: 120,
    image: "/img6.avif",
    badge: "Limited",
    isFavourite: true,
    latest: false,
    bestSeller: true,
    category: "Watch",
  },
  {
    id: 7,
    name: "Portable Power Bank",
    price: 29.99,
    rating: 4,
    numberRating: 75,
    image: "/img7.avif",
    badge: "New Arrival",
    isFavourite: false,
    latest: false,
    bestSeller: true,
    category: "Phone",
  },
  {
    id: 8,
    name: "Gaming Headset",
    price: 69.99,
    rating: 5,
    numberRating: 132,
    image: "/img8.avif",
    badge: "Top Rated",
    isFavourite: true,
    latest: false,
    bestSeller: true,
    category: "Headphone",
  },
  {
    id: 9,
    name: "4K Web Camera",
    price: 79.99,
    rating: 4,
    numberRating: 56,
    image: "/img9.avif",
    badge: "Exclusive",
    isFavourite: false,
    latest: false,
    bestSeller: true,
    category: "Camera",
  },
  {
    id: 10,
    name: "Ergonomic Laptop Stand",
    price: 34.99,
    rating: 4,
    numberRating: 68,
    image: "/img10.avif",
    badge: "Classic",
    isFavourite: true,
    latest: false,
    bestSeller: true,
    category: "Computer",
  },
  {
    id: 11,
    name: "Sony Wireless Headphones",
    price: 348.0,
    rating: 4.7,
    numberRating: 210,
    image: "/img11.avif",
    badge: "Best Seller",
    isFavourite: false,
    latest: true,
    bestSeller: true,
    category: "Headphone",
  },
  {
    id: 12,
    name: "Apple Pro 16-inch",
    price: 2399.0,
    rating: 4.8,
    numberRating: 95,
    image: "/img12.avif",
    badge: "New Arrival",
    isFavourite: true,
    latest: true,
    bestSeller: false,
    category: "Computer",
  },
  {
    id: 13,
    name: "Samsung S21 Ultra 5G",
    price: 1199.99,
    rating: 4.6,
    numberRating: 182,
    image: "/img13.avif",
    badge: "Trending",
    isFavourite: true,
    latest: true,
    bestSeller: true,
    category: "Phone",
  },
  {
    id: 14,
    name: "Dell XPS 13 Laptop",
    price: 999.99,
    rating: 4.5,
    numberRating: 125,
    image: "/img14.avif",
    badge: "Top Rated",
    isFavourite: false,
    latest: false,
    bestSeller: true,
    category: "Computer",
  },
  {
    id: 15,
    name: "Bose 35 II Headphones",
    price: 299.99,
    rating: 4.7,
    numberRating: 140,
    image: "/img15.avif",
    badge: "Limited",
    isFavourite: true,
    latest: false,
    bestSeller: true,
    category: "Headphone",
  },
  {
    id: 16,
    name: "Apple iPhone 12 Pro Max",
    price: 1099.0,
    rating: 4.6,
    numberRating: 195,
    image: "/img16.avif",
    badge: "Exclusive",
    isFavourite: false,
    latest: true,
    bestSeller: true,
    category: "Phone",
  },
  {
    id: 17,
    name: "Sony PlayStation 5 Console",
    price: 499.99,
    rating: 4.9,
    numberRating: 250,
    image: "/img17.avif",
    badge: "Limited Edition",
    isFavourite: true,
    latest: true,
    bestSeller: true,
    category: "Gamepad",
  },
  {
    id: 18,
    name: "Apple Watch Series 6",
    price: 399.0,
    rating: 4.5,
    numberRating: 120,
    image: "/img18.avif",
    badge: "Top Rated",
    isFavourite: false,
    latest: true,
    bestSeller: true,
    category: "Watch",
  },
  {
    id: 19,
    name: "GoPro HERO9 Black",
    price: 399.99,
    rating: 4.8,
    numberRating: 160,
    image: "/img19.avif",
    badge: "Adventure Ready",
    isFavourite: true,
    latest: true,
    bestSeller: false,
    category: "Camera",
  },
  {
    id: 20,
    name: "Microsoft Surface Pro 7",
    price: 749.99,
    rating: 4.4,
    numberRating: 110,
    image: "/img20.avif",
    badge: "Business Choice",
    isFavourite: false,
    latest: false,
    bestSeller: true,
    category: "Computer",
  },
];
